[package]
name = "octox"
version = "0.1.0"
authors = ["Hayato Ohhashi <o8@vmm.dev>"]
edition = "2021"

[lib]
name = "kernel"
path = "src/kernel/lib.rs"

[[bin]]
name = "kernel"
path = "src/kernel/main.rs"

[dependencies]
array-macro = "2.1.0"
